### ISSUE TITLE
Add an option to disable maintenance service

### ISSUE THREAD

**Issue by ashald** [wifwucite/esphome-ble-controller#10]
Hi!

First of all, thanks a lot for an amazing component! It's a shame something like this is not available in the official ESPHome.

I have to ESP32 nodes, and I'm setting up one with `esphome-ble-controller` to expose some sensors (indoor air quality etc), and I plan to use the other one with [`ble_client`](https://esphome.io/components/ble_client.html) to consume the data, so that it could update the attached eInk display every time it awakes from deep sleep.

The issues is that [`ble_client`](https://esphome.io/components/ble_client.html) doesn't support secure connections, and this means I'd have to run `esphome-ble-controller` in an insecure mode, potentially exposing my node for others to abuse. I'm looking to address this issue either by disabling the maintenance service so that even if someone connects they can only see the sensor data, or hiding the advertisement so that it's possible to connect to `esphome-ble-controller` node only if you know its MAC address.

Thanks!

**Comment by wifwucite** [comment]
Hi,
Sounds like a valid enhancement, let me have a look.

**Comment by ashald** [comment]
FWIW, I gave it a try and got it workin - I submitted #13 in case it will be of any help.
If you'd rather do it differently please reject the PR and I'd gladly use it the way you'd implement it.
Thanks!

**Comment by wifwucite** [comment]
Thanks again for the efforts, please have a look if my implementation works for you. Then I will generate a release ...

**Comment by ashald** [comment]
It's working great, thanks a lot! 😊
