### ISSUE TITLE
BLE MAC Address

### ISSUE THREAD

**Issue by ashald** [wifwucite/esphome-ble-controller#12]
Is there a way to get the MAC address of the BLE controller? Could it be configured, logged, or reported via maintenance service?

Thanks!

**Comment by wifwucite** [comment]
I think logging should be an option. However, tools like LightBlue or nrfConnect should display the address as well ...

**Comment by wifwucite** [comment]
Done, the device's address is now logged as part of the configuration.

**Comment by ashald** [comment]
Thanks a lot!

FWIW, Apple devices (iOS, macOS etc) seem to hide MAC addresses for BLE devices, so I couldn't retrieve the MAC address for my MCU with any of the app I tried. I ended up using a custom sensor:

```
#include "esphome.h"
#include <BLEDevice.h>


class BleAddress : public PollingComponent, public TextSensor {
 public:
  // constructor
  BleAddress() : PollingComponent(15000) {}

  float get_setup_priority() const override { return esphome::setup_priority::LATE; }

  void setup() override {
    // This will be called by App.setup()
  }
  void update() override {
    publish_state(BLEDevice::getAddress().toString());
  }
};
```
but It's much more convenient when you can get the address from ble-controller logs!
