### ISSUE TITLE
RSSI sensor

### ISSUE THREAD

**Issue by sanyatuning** [wifwucite/esphome-ble-controller#2]
Hi @wifwucite!

I would like to create a smart lock with ESPhome.
(I dont want to publish a beacon with my phone)
My idea is to pair my andorid phone with the esphome device, for security reasons.
I guess it will auto-connect if in range.
I need to measure the rssi value to calculate distance, then set it as a sensor value.

I can't get pairing with the core esphome ble server.
What do you think about this?
Is it possible anyway and with your controller lib?

**Comment by sanyatuning** [comment]
I tried your code, but it does not connect automatically, just with the BLE scanner app

**Comment by wifwucite** [comment]
Well, technically the controller is a BLE server, I.e. it advertises services and waits for a BLE client like your phone to connect. So the client has to start the connection process. That means you need an app on your phone. Or you could try the BLE client from ESPHome, which can also do presence detection and measure RSSI values. However that is all based on MAC addresses, which can be spoofed. So for me this would be too insecure for a lock.
