### ISSUE TITLE
Is this component integrated in official or dev release?

### ISSUE THREAD

**Issue by manju-rn** [wifwucite/esphome-ble-controller#3]
I see this communication in the PR and was under the impression that this component is integrated within esphome, possible as esp32_ble?  As I checked now, it only exposes improv components

<https://github.com/esphome/esphome/pull/1807#issuecomment-851268865>

**Comment by wifwucite** [comment]
Hi, no this component is not part of the standard. The component in the standard has borrowed some ideas from this component, and then unfortunately they diverged. I think the actual implementations are quite different.

**Comment by manju-rn** [comment]
Noted. It'a bummer as this component is awesome!   The BLE Server component of esphome currently just hosts the improv component.
