### ISSUE TITLE
Switch / Sensor data in Advertisement Beacon

### ISSUE THREAD

**Issue by manju-rn** [wifwucite/esphome-ble-controller#5]
I am using this module as BLE Server quite successfully. However, I realized I would need multiple client to use this.  Hence can you check if the "Exposed" switch or sensor data can be pushed as value for Advertisement data?  This way I could have multiple devices utilize this. I understand that depending upon the beacon interval, the sensor data may be a bit delayed, but thats okay

I am also trying to check how can I modify to incorporate the same, but I guess you would have already though about it

**Comment by wifwucite** [comment]
I think it would require some substantial refactoring of the existing code, currently the advertisement data is set up only once during initialization. 
There seems to be some broadcasting feature in BLE 5.0, but I have never tried it. I found some [ESP32 Beacon tutorial](https://circuitdigest.com/microcontroller-projects/esp32-based-bluetooth-ibeacon). Something along these lines might work, but that‘s probably work for a different component. ;-) And the amount of data that can be exposed could be limited.
