### ISSUE TITLE
I tried your example I get this, can you help? thanks!

### ISSUE THREAD

**Issue by maker999** [wifwucite/esphome-ble-controller#7]
Compiling .pioenvs\core_v2\src\esphome\components\binary_sensor\automation.cpp.o
Compiling .pioenvs\core_v2\src\esphome\components\binary_sensor\binary_sensor.cpp.o
Compiling .pioenvs\core_v2\src\esphome\components\binary_sensor\filter.cpp.o
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
*** [.pioenvs\core_v2\src\esphome\components\binary_sensor\automation.cpp.o] Error 1
Compiling .pioenvs\core_v2\src\esphome\components\captive_portal\captive_portal.cpp.o
*** [.pioenvs\core_v2\src\esphome\components\binary_sensor\binary_sensor.cpp.o] Error 1
*** [.pioenvs\core_v2\src\esphome\components\binary_sensor\filter.cpp.o] Error 1
xtensa-esp32-elf-g++: fatal error: no input files
compilation terminated.
*** [.pioenvs\core_v2\src\esphome\components\captive_portal\captive_portal.cpp.o] Error 1

**Comment by wifwucite** [comment]
Well, it seems that all the errors are coming from core ESPHome components like binary sensor or captive portal. Can you remove the BLE component from your yaml configuration and see if you are still getting errors.

**Comment by maker999** [comment]
when I remove the BLE component I get no errors

**Comment by wifwucite** [comment]
Ok, can you post the yaml file that you use (without secrets), please? And are you using the latest ESPHome version?

**Comment by maker999** [comment]
esphome:
  name: core_v2
  platform: ESP32
  board: nodemcu-32s
  libraries: 
    - Wire
    #- https://github.com/wifwucite/esphome-ble-controller
  includes:
    - uart_multi_esp.h

external_components:
  - source: github://wifwucite/esphome-ble-controller

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - if:
              condition:
                lambda: |-
                  auto time = id(sntp_time).now();
                  ESP_LOGD("main", "The current dawn time is %2d:%2d", id(dawn_hour), id(dawn_minute));
                  return (time.hour == id(dawn_hour))&&(time.minute == id(dawn_minute))&&id(dawn_enable);
              then:
              - script.execute:
                  id: dawn_simulation

wifi:
  networks:
  - ssid: "my ssid"
    password: "my password"


captive_portal:

# Enable logging
logger:
  level: DEBUG #makes uart stream available in esphome logstream

# Enable Home Assistant API
#api:
ota:

globals:
  - id: active
    type: int
    initial_value: '0'  # different numbers represent different light modes
  - id: dawn_hour
    type: int
    restore_value: yes
    initial_value: '19'
  - id: dawn_minute
    type: int
    restore_value: yes
    initial_value: '30'
  - id: dawn_duration
    type: int
    restore_value: yes
    initial_value: '30'
  - id: uart_msg
    type: char[20]
    initial_value: "{'i','d','l','e'}"
  - id: last_msg
    type: std::string
  - id: dawn_enable
    type: bool
    initial_value: 'false'

pca9685:
  frequency: 500

i2c:
  sda: 18
  scl: 19
  scan: True
  id: pwm_bus

switch:
  - platform: template
    name: "Template Switch"
    optimistic: true
    id: template_switch
  - platform: template
    name: "Dawn Switch"
    id: dawn_switch
    lambda: |-
      if (id(active)) {
        return true;
      } else {
        return false;
      }
    on_turn_on:
      - if:
          condition:
            lambda: 'return (id(active) == 1);'
          then:
            - script.execute:
                id: dawn_simulation
    on_turn_off:
      - script.execute:
          id: stop_all_scripts
      - script.execute:
          id: turn_off_all_lights
  - platform: template
    name: "set_dawn"
    lambda: |-
      if (id(esp_text).state.find("set dawn") !=std::string::npos) {
        id(dawn_hour) = atoi( id(esp_text).state.substr( id(esp_text).state.find(":") - 2,  2).c_str() );
        id(dawn_minute) = atoi( id(esp_text).state.substr( id(esp_text).state.find(":") + 1 , 2).c_str() );
        ESP_LOGI("STATE", "The new dawn time is %2d:%2d", id(dawn_hour), id(dawn_minute));
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
        //if(id(last_msg).compare(id(esp_text).state)!=0){
        //  id(last_msg).assign(id(esp_text).state);
        //}
  - platform: template
    name: "dawn_toggle"
    lambda: |-
      if (id(esp_text).state == "dawn on") {
        id(dawn_enable) = true;
        ESP_LOGI("STATE", "dawn: ON");
        return true;
      } else if (id(esp_text).state == "dawn off"){
        id(dawn_enable) = false;
        ESP_LOGI("STATE", "dawn: OFF");
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
        //if(id(last_msg).compare(id(esp_text).state)!=0){
        //  id(last_msg).assign(id(esp_text).state);
        //}
  - platform: template
    name: "shower_switch"
    id: shower_switch
    lambda: |-
      if(id(esp_text).state == "shower") {
        id(light_shower_scene).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
  - platform: template
    name: "reading_switch"
    lambda: |-
      if(id(esp_text).state == "reading") {
        id(reading_scene).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
  - platform: template
    name: "reading_switch"
    lambda: |-
      if(id(esp_text).state == "idle") {
        id(turn_off_all_lights).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();

# light configuration
output:
  - platform: pca9685
    id: 'pca9685_hub0'
    channel: 0
  - platform: pca9685
    id: 'pca9685_hub1'
    channel: 1
  - platform: pca9685
    id: 'pca9685_hub2'
    channel: 2
  - platform: pca9685
    id: 'pca9685_hub3'
    channel: 3
  - platform: pca9685
    id: 'pca9685_hub4'
    channel: 4
  - platform: pca9685
    id: 'pca9685_hub5'
    channel: 5
  - platform: pca9685
    id: 'pca9685_hub6'
    channel: 6
  - platform: pca9685
    id: 'pca9685_hub7'
    channel: 7
  - platform: pca9685
    id: 'pca9685_hub8'
    channel: 8
  - platform: pca9685
    id: 'pca9685_hub9'
    channel: 9
  - platform: pca9685
    id: 'pca9685_hub10'
    channel: 10
  - platform: pca9685
    id: 'pca9685_hub11'
    channel: 11
  - platform: pca9685
    id: 'pca9685_hub12'
    channel: 12
  - platform: pca9685
    id: 'pca9685_hub13'
    channel: 13
  - platform: pca9685
    id: 'pca9685_hub14'
    channel: 14
  - platform: pca9685
    id: 'pca9685_hub15'
    channel: 15

light:
  - platform: rgbw
    id: indirect_edge_rgbw
    name: "Indirect Edge RGBW"
    red: pca9685_hub0
    green: pca9685_hub1
    blue: pca9685_hub2
    white: pca9685_hub3
  - platform: rgbw
    id: indirect_center_rgbw
    name: "Indirect Center RBGW"
    red: pca9685_hub4
    green: pca9685_hub5
    blue: pca9685_hub6
    white: pca9685_hub7
  - platform: monochromatic
    id: indirect_center_ww
    name: "Indirect Center WW"
    output: pca9685_hub8
  - platform: monochromatic
    id: indirect_center_inner_cw
    name: "Indirect Center Inner CW"
    output: pca9685_hub9
  - platform: monochromatic
    id: indirect_center_outer_cw
    name: "Indirect Center Outer CW"
    output: pca9685_hub10
  # direct lights
  - platform: monochromatic
    id: direct_panel_front_edge_cw
    name: "Direct Panel Front Edge CW"
    output: pca9685_hub11
  - platform: monochromatic
    id: direct_panel_back_edge_cw
    name: "Direct Panel Back Edge CW"
    output: pca9685_hub12



script:
  # stop all scripts
  - id: stop_all_scripts
    then:
      - logger.log: "Stopping all running scripts."
      - script.stop:
          id: dawn_simulation
      - logger.log: "Stopped all running scripts."
  - id: turn_off_all_lights
    then:
      - logger.log: "Turning off all lights."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_edge_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: indirect_center_ww
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - logger.log: "Turned off all lights."
  # dawn simulation
  - id: dawn_simulation
    then:
      - logger.log: "Starting dawn simulation."
      # phase 1/10
      - light.turn_on: 
          id: indirect_center_rgbw
          red: 0%
          blue: 10%
          green: 0%
          white: 0%
          transition_length: !lambda |-
            // output value must be in range 0 - 1.0
            return id(dawn_duration)*60/27;
      - delay: 1s
      # phase 2/20
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 50%
          red: 25%
          green: 25%
          transition_length: 1s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 50%
          green: 25%
          transition_length: 1s
      - delay: 1s
      # phase 3&4/10
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 100%
          white: 50%
          transition_length: 2s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 100%
          green: 50%
          white: 50%
          transition_length: 2s
      - delay: 2s
      # phase 5/10
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 100%
          white: 100%
          transition_length: 1s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 100%
          green: 50%
          white: 100%
          transition_length: 1s
      - delay: 1s
      # phase 6&7/10
      - light.turn_on:
          id: indirect_center_inner_cw
          brightness: 50%
          transition_length: 2s
      - delay: 2s
      # phase 8&9/10
      - light.turn_on:
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 2s
      - light.turn_on:
          id: indirect_center_outer_cw
          brightness: 50%
          transition_length: 2s
      - delay: 2s
      # phase 10/10
      - light.turn_on:
          id: indirect_center_outer_cw
          brightness: 100%
          transition_length: 1s
      - light.turn_on:
          id: indirect_center_ww
          brightness: 100%
          transition_length: 1s
      - delay: 1s
      - logger.log: "Finished dawn simulation."
  # reading scene
  - id: reading_scene
    then:
      - logger.log: "Entering reading scene."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - light.turn_on:
          id: indirect_center_ww
          brightness: 10%
      - light.turn_on:
          id: indirect_edge_rgbw
          brightness: 10%
          red: 100%
          green: 50%
          blue: 0%
      - logger.log: "Entered reading scene."
    # light shower
  - id: light_shower_scene
    then:
      - logger.log: "Entering light shower scene."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_edge_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: indirect_center_ww
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - light.turn_on: 
          id: indirect_center_rgbw
          brightness: 100%
          blue: 100%
          red: 100%
          green: 100%
          white: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_edge_rgbw
          brightness: 100%
          blue: 100%
          red: 100%
          green: 100%
          white: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_outer_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_ww
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: direct_panel_front_edge_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: direct_panel_back_edge_cw
          brightness: 100%
          transition_length: 3s
      - logger.log: "Entered light shower scene."



uart:
  # Remote ESP 
  - id: esp_uart
    rx_pin: 14
    tx_pin: 27
    baud_rate: 9600


text_sensor:
  - platform: custom
    lambda: |-
      auto my_custom_sensor = new UartMultiESP(id(esp_uart));
      App.register_component(my_custom_sensor);
      return {my_custom_sensor};
    text_sensors:
      id: "esp_text"

binary_sensor:
  - platform: gpio
    id: test_button
    pin: 
      number: GPIO34
      inverted: True
    on_click:
      - min_length: 100ms
        max_length: 500ms
        then:
          - logger.log: "test button pressed."
          - lambda: |-
              id(active) = id(active) ? 0 : 1;
              ESP_LOGI("STATE", "active entered state %d", id(active));

esp32_ble:

esp32_ble_controller:
  services:
  - service: "4fafc201-1fb5-459e-8fcc-c5c9c331915d"
    characteristics:
      - characteristic: "beb5483e-36e1-4688-b7f5-ea07361b26ab"
        exposes: template_switch

**Comment by maker999** [comment]
`esphome:
  name: core_v2
  platform: ESP32
  board: nodemcu-32s
  libraries: 
    - Wire
    #- https://github.com/wifwucite/esphome-ble-controller
  includes:
    - uart_multi_esp.h

external_components:
  - source: github://wifwucite/esphome-ble-controller

time:
  - platform: sntp
    id: sntp_time
    on_time:
      - seconds: 0
        minutes: /1
        then:
          - if:
              condition:
                lambda: |-
                  auto time = id(sntp_time).now();
                  ESP_LOGD("main", "The current dawn time is %2d:%2d", id(dawn_hour), id(dawn_minute));
                  return (time.hour == id(dawn_hour))&&(time.minute == id(dawn_minute))&&id(dawn_enable);
              then:
              - script.execute:
                  id: dawn_simulation

wifi:
  networks:
  - ssid: "my ssid"
    password: "my pw"
  

captive_portal:

# Enable logging
logger:
  level: DEBUG #makes uart stream available in esphome logstream

# Enable Home Assistant API
#api:
ota:

globals:
  - id: active
    type: int
    initial_value: '0'  # different numbers represent different light modes
  - id: dawn_hour
    type: int
    restore_value: yes
    initial_value: '19'
  - id: dawn_minute
    type: int
    restore_value: yes
    initial_value: '30'
  - id: dawn_duration
    type: int
    restore_value: yes
    initial_value: '30'
  - id: uart_msg
    type: char[20]
    initial_value: "{'i','d','l','e'}"
  - id: last_msg
    type: std::string
  - id: dawn_enable
    type: bool
    initial_value: 'false'

pca9685:
  frequency: 500

i2c:
  sda: 18
  scl: 19
  scan: True
  id: pwm_bus

switch:
  - platform: template
    name: "Template Switch"
    optimistic: true
    id: template_switch
  - platform: template
    name: "Dawn Switch"
    id: dawn_switch
    lambda: |-
      if (id(active)) {
        return true;
      } else {
        return false;
      }
    on_turn_on:
      - if:
          condition:
            lambda: 'return (id(active) == 1);'
          then:
            - script.execute:
                id: dawn_simulation
    on_turn_off:
      - script.execute:
          id: stop_all_scripts
      - script.execute:
          id: turn_off_all_lights
  - platform: template
    name: "set_dawn"
    lambda: |-
      if (id(esp_text).state.find("set dawn") !=std::string::npos) {
        id(dawn_hour) = atoi( id(esp_text).state.substr( id(esp_text).state.find(":") - 2,  2).c_str() );
        id(dawn_minute) = atoi( id(esp_text).state.substr( id(esp_text).state.find(":") + 1 , 2).c_str() );
        ESP_LOGI("STATE", "The new dawn time is %2d:%2d", id(dawn_hour), id(dawn_minute));
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
        //if(id(last_msg).compare(id(esp_text).state)!=0){
        //  id(last_msg).assign(id(esp_text).state);
        //}
  - platform: template
    name: "dawn_toggle"
    lambda: |-
      if (id(esp_text).state == "dawn on") {
        id(dawn_enable) = true;
        ESP_LOGI("STATE", "dawn: ON");
        return true;
      } else if (id(esp_text).state == "dawn off"){
        id(dawn_enable) = false;
        ESP_LOGI("STATE", "dawn: OFF");
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
        //if(id(last_msg).compare(id(esp_text).state)!=0){
        //  id(last_msg).assign(id(esp_text).state);
        //}
  - platform: template
    name: "shower_switch"
    id: shower_switch
    lambda: |-
      if(id(esp_text).state == "shower") {
        id(light_shower_scene).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
  - platform: template
    name: "reading_switch"
    lambda: |-
      if(id(esp_text).state == "reading") {
        id(reading_scene).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();
  - platform: template
    name: "reading_switch"
    lambda: |-
      if(id(esp_text).state == "idle") {
        id(turn_off_all_lights).execute();
        return true;
      } else {
        return false;
      }
    on_turn_on:
      lambda: |-
        id(esp_text).state.clear();

# light configuration
output:
  - platform: pca9685
    id: 'pca9685_hub0'
    channel: 0
  - platform: pca9685
    id: 'pca9685_hub1'
    channel: 1
  - platform: pca9685
    id: 'pca9685_hub2'
    channel: 2
  - platform: pca9685
    id: 'pca9685_hub3'
    channel: 3
  - platform: pca9685
    id: 'pca9685_hub4'
    channel: 4
  - platform: pca9685
    id: 'pca9685_hub5'
    channel: 5
  - platform: pca9685
    id: 'pca9685_hub6'
    channel: 6
  - platform: pca9685
    id: 'pca9685_hub7'
    channel: 7
  - platform: pca9685
    id: 'pca9685_hub8'
    channel: 8
  - platform: pca9685
    id: 'pca9685_hub9'
    channel: 9
  - platform: pca9685
    id: 'pca9685_hub10'
    channel: 10
  - platform: pca9685
    id: 'pca9685_hub11'
    channel: 11
  - platform: pca9685
    id: 'pca9685_hub12'
    channel: 12
  - platform: pca9685
    id: 'pca9685_hub13'
    channel: 13
  - platform: pca9685
    id: 'pca9685_hub14'
    channel: 14
  - platform: pca9685
    id: 'pca9685_hub15'
    channel: 15

light:
  - platform: rgbw
    id: indirect_edge_rgbw
    name: "Indirect Edge RGBW"
    red: pca9685_hub0
    green: pca9685_hub1
    blue: pca9685_hub2
    white: pca9685_hub3
  - platform: rgbw
    id: indirect_center_rgbw
    name: "Indirect Center RBGW"
    red: pca9685_hub4
    green: pca9685_hub5
    blue: pca9685_hub6
    white: pca9685_hub7
  - platform: monochromatic
    id: indirect_center_ww
    name: "Indirect Center WW"
    output: pca9685_hub8
  - platform: monochromatic
    id: indirect_center_inner_cw
    name: "Indirect Center Inner CW"
    output: pca9685_hub9
  - platform: monochromatic
    id: indirect_center_outer_cw
    name: "Indirect Center Outer CW"
    output: pca9685_hub10
  # direct lights
  - platform: monochromatic
    id: direct_panel_front_edge_cw
    name: "Direct Panel Front Edge CW"
    output: pca9685_hub11
  - platform: monochromatic
    id: direct_panel_back_edge_cw
    name: "Direct Panel Back Edge CW"
    output: pca9685_hub12



script:
  # stop all scripts
  - id: stop_all_scripts
    then:
      - logger.log: "Stopping all running scripts."
      - script.stop:
          id: dawn_simulation
      - logger.log: "Stopped all running scripts."
  - id: turn_off_all_lights
    then:
      - logger.log: "Turning off all lights."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_edge_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: indirect_center_ww
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - logger.log: "Turned off all lights."
  # dawn simulation
  - id: dawn_simulation
    then:
      - logger.log: "Starting dawn simulation."
      # phase 1/10
      - light.turn_on: 
          id: indirect_center_rgbw
          red: 0%
          blue: 10%
          green: 0%
          white: 0%
          transition_length: !lambda |-
            // output value must be in range 0 - 1.0
            return id(dawn_duration)*60/27;
      - delay: 1s
      # phase 2/20
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 50%
          red: 25%
          green: 25%
          transition_length: 1s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 50%
          green: 25%
          transition_length: 1s
      - delay: 1s
      # phase 3&4/10
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 100%
          white: 50%
          transition_length: 2s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 100%
          green: 50%
          white: 50%
          transition_length: 2s
      - delay: 2s
      # phase 5/10
      - light.turn_on:
          id: indirect_center_rgbw
          blue: 100%
          white: 100%
          transition_length: 1s
      - light.turn_on:
          id: indirect_edge_rgbw
          red: 100%
          green: 50%
          white: 100%
          transition_length: 1s
      - delay: 1s
      # phase 6&7/10
      - light.turn_on:
          id: indirect_center_inner_cw
          brightness: 50%
          transition_length: 2s
      - delay: 2s
      # phase 8&9/10
      - light.turn_on:
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 2s
      - light.turn_on:
          id: indirect_center_outer_cw
          brightness: 50%
          transition_length: 2s
      - delay: 2s
      # phase 10/10
      - light.turn_on:
          id: indirect_center_outer_cw
          brightness: 100%
          transition_length: 1s
      - light.turn_on:
          id: indirect_center_ww
          brightness: 100%
          transition_length: 1s
      - delay: 1s
      - logger.log: "Finished dawn simulation."
  # reading scene
  - id: reading_scene
    then:
      - logger.log: "Entering reading scene."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - light.turn_on:
          id: indirect_center_ww
          brightness: 10%
      - light.turn_on:
          id: indirect_edge_rgbw
          brightness: 10%
          red: 100%
          green: 50%
          blue: 0%
      - logger.log: "Entered reading scene."
    # light shower
  - id: light_shower_scene
    then:
      - logger.log: "Entering light shower scene."
      - light.turn_off: indirect_center_rgbw
      - light.turn_off: indirect_edge_rgbw
      - light.turn_off: indirect_center_inner_cw
      - light.turn_off: indirect_center_outer_cw
      - light.turn_off: indirect_center_ww
      - light.turn_off: direct_panel_back_edge_cw
      - light.turn_off: direct_panel_front_edge_cw
      - light.turn_on: 
          id: indirect_center_rgbw
          brightness: 100%
          blue: 100%
          red: 100%
          green: 100%
          white: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_edge_rgbw
          brightness: 100%
          blue: 100%
          red: 100%
          green: 100%
          white: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_inner_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_outer_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: indirect_center_ww
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: direct_panel_front_edge_cw
          brightness: 100%
          transition_length: 3s
      - light.turn_on: 
          id: direct_panel_back_edge_cw
          brightness: 100%
          transition_length: 3s
      - logger.log: "Entered light shower scene."



uart:
  # Remote ESP 
  - id: esp_uart
    rx_pin: 14
    tx_pin: 27
    baud_rate: 9600


text_sensor:
  - platform: custom
    lambda: |-
      auto my_custom_sensor = new UartMultiESP(id(esp_uart));
      App.register_component(my_custom_sensor);
      return {my_custom_sensor};
    text_sensors:
      id: "esp_text"

binary_sensor:
  - platform: gpio
    id: test_button
    pin: 
      number: GPIO34
      inverted: True
    on_click:
      - min_length: 100ms
        max_length: 500ms
        then:
          - logger.log: "test button pressed."
          - lambda: |-
              id(active) = id(active) ? 0 : 1;
              ESP_LOGI("STATE", "active entered state %d", id(active));

esp32_ble:

esp32_ble_controller:
  services:
  - service: "4fafc201-1fb5-459e-8fcc-c5c9c331915d"
    characteristics:
      - characteristic: "beb5483e-36e1-4688-b7f5-ea07361b26ab"
        exposes: template_switch`

**Comment by maker999** [comment]
yaml files couldn't be uploaded so I uploaded a text file
[ble_test.txt](https://github.com/wifwucite/esphome-ble-controller/files/7456273/ble_test.txt)

**Comment by wifwucite** [comment]
I have tested your file with minor changes with esphome version 2021.10.3 and Espressif platform 3.3.2. It compiled without any issues. For some template switch I had to add "optimistic: true", otherwise the validation of the yaml failed.
Can you confirm that you have the latest ESPHome version?

**Comment by maker999** [comment]
I have the version 2021.9.0 because the latest one doesnt run on windows. Is it possible to use this component with this version?

**Comment by wifwucite** [comment]
Yes, it should, but you have to use the previous release 0.4.0, which has the same functionality as the current one.

**Comment by wifwucite** [comment]
Have you tried the previous release?

**Comment by maker999** [comment]
I faced other problems so I had to set everything up from beginning. now with the latest esphome(2021.10.3) it compiles ok.

**Comment by wifwucite** [comment]
Sounds good. :-)
