### ISSUE TITLE
I could use this library and suddenly it started giving me this error, could you help?

### ISSUE THREAD

**Issue by maker999** [wifwucite/esphome-ble-controller#8]
src/esphome/components/esp32_ble_controller/ble_command.cpp: In member function 'virtual void esphome::esp32_ble_controller::BLECommandLogLevel::execute(const std::vector<std::__cxx11::basic_string<char> >&) const':
src/esphome/components/esp32_ble_controller/ble_command.cpp:144:33: error: 'parse_number' was not declared in this scope
     const optional<int> level = parse_number<int>(log_level);
                                 ^
src/esphome/components/esp32_ble_controller/ble_command.cpp:144:46: error: expected primary-expression before 'int'
     const optional<int> level = parse_number<int>(log_level);
                                              ^
*** [.pioenvs/sound_unit/src/esphome/components/esp32_ble_controller/ble_command.cpp.o] Error 1

**Comment by wifwucite** [comment]
Hi,
Yes, I had to make a change for the new ESPHome version. Unfortunately they are breaking backward compatibility with every new release these days. So either you switch to ESPHome 2021.11 or you go back to version v0.5.0 of this library, which runs with ESPHome 2021.10.
